### ISSUE TITLE
Handling ChunkLoadError: Loading chunk XXX failed.

### ISSUE THREAD

**Issue by Maybach91** [wesselvanree/shopify-theme-tailwind#9]
When deploying a new version to Shopify after running the build command, i get the following error:

```
Refused to execute script from 'https://cdn.shopify.com/s/files/1/0612/6878/7409/t/5/assets/497' because its MIME type ('application/octet-stream') is not executable, and strict MIME type checking is enabled.
  
ChunkLoadError: Loading chunk 497 failed.
```

I don’t really know how or why it happens, since all the old chunks are still available in the `Assets` folder.
![image](https://user-images.githubusercontent.com/1867543/162164067-691f65df-40d4-4c92-812a-f81761c637b1.png)
(but not visible via Admin Panel, but in my IDE)

Any tips how to solve this? How can i prevent creating chunks? I thought only `entries/*` files are compiled.

Thats my folder structure:
![image](https://user-images.githubusercontent.com/1867543/162181938-cb13a55a-c695-4b09-8460-b2a1a7038061.png)

index.tsx:
```typescript

// App main
const main = async () => {
  try {
    // Import Vendors
    const { default: vendors } = await import('./_vendors');
    await vendors();

    // Import Components
    const { default: components } = await import('./_components');
    await components();

  } catch (e) {
    // eslint-disable-next-line no-console
    console.error(e);
  }
};

// Execute async function
// eslint-disable-next-line
main().then(() => {});
export {}

```

Webpack Output:

```
  modules by path ./src/ 8.66 KiB
    modules by path ./src/js/*.tsx 6.74 KiB
      ./src/js/_vendors.tsx 1.18 KiB [built] [code generated]
      ./src/js/_components.tsx + 6 modules 2.91 KiB [built] [code generated]
      ./src/js/slider.tsx 2.65 KiB [built] [code generated]
    ./src/entries/index.tsx 1.58 KiB [built] [code generated]
    ./src/vendors/alpinejs.ts 342 bytes [built] [code generated]
```
---
**EDIT**:

Kinda got it work. The problem was, that the chunk files didn’t have any extension. Something is wrong with the `webpack.config.js` @wesselvanree 

I changed the following to make it work:

`filename: '[name].js',` (added `.js`)
  
`targetFile = targetFile + '.bundle'` (removed `.js`)

**Comment by wesselvanree** [comment]
Hi @Maybach91!

It is true that webpack only looks for files in the `entries` folder. But when it encounters a [dynamic import](https://webpack.js.org/guides/code-splitting/#dynamic-imports), webpack creates a separate bundle for that dynamic import, even if the imported module is not in the `entries` folder.

Did your code fix the error?
I have updated [`webpack.config.js`](https://github.com/wesselvanree/shopify-theme-tailwind/blob/resolve-chunk-load-error/webpack.config.js), could you try the config on branch `resolve-chunk-load-error` and let me know if it works?

**Comment by wesselvanree** [comment]
I will close this issue as the error does not occur in my environment anymore. Please reopen this issue if the issue has not been resolved in your case.

**Comment by wesselvanree** [comment]
Hi @Maybach91,

So the ChunkLoadError does not occur anymore?

Those chunks are a feature of Webpack, without those chunks your dynamic imports would not work. So I don't think you want to disable that. If you want to execute the async functions without those chunks, I would create an entry in de entries folder that uses regular imports, and add a script tag with the async attribute to a liquid file (if global in `theme.liquid`). So you would create a webpack entry that looks something like this:

```ts
import vendors from '../js/_vendors'
import components from '../js/_components'

async function initializeModules() {
  await vendors()
  await components()
}

initializeModules()
```

And then add the resulting bundle to your liquid file:

```liquid
<script src="{{ 'your-file.bundle.js' | asset_url }}" async></script>
```

Please let me know whether this solves your problem!

**Comment by wesselvanree** [comment]
You're welcome! Good luck with developing your theme!
